### ISSUE TITLE
Length, Delete?

### ISSUE THREAD

**Issue by ciez** [Daniel-Diaz/sorted-list#1]
Thank you very much for this lib. It is very useful.

Is there any chance to add (list) length & delete (specified element(s)) functions?

**Comment by Daniel-Diaz** [comment]
You have `length` through [`Data.Foldable`](http://downloads.haskell.org/~ghc/latest/docs/html/libraries/base-4.8.2.0/Data-Foldable.html). I will add delete.

**Comment by Daniel-Diaz** [comment]
Done.

https://github.com/Daniel-Diaz/sorted-list/commit/2ca35623945fee66aa7c946d38081e23b4a42ce0
