### ISSUE TITLE
intersection & union?

### ISSUE THREAD

**Issue by jchia** [Daniel-Diaz/sorted-list#4]
It would be helpful to have functions for getting the intersection of sorted lists and union of sorted lists.

**Comment by Daniel-Diaz** [comment]
Thanks. I will get those implemented.

**Comment by Daniel-Diaz** [comment]
Closed by https://github.com/Daniel-Diaz/sorted-list/commit/53f9929c8ae4a351d3cdf30f8ef05e89a947c4d3.
